Revert D89801436 (#47)
Summary:

This diff reverts D89801436
ERROR: No matching distribution found for isort==7.0.0
https://www.internalfb.com/sandcastle/workflow/4548635623657729722

Depends on D89801436

Reviewed By: jj10306

Differential Revision: D93160151